import { strict as assert } from "node:assert";
import { test } from "node:test";

import { PROGRAMS, offerablePrograms } from "./registry.ts";
import { assembleProgram } from "./assemble.ts";
import { visibleQuestions } from "./validate.ts";
import type { Answers, CompanyContext, ProgramTemplate, Section } from "./types.ts";

/**
 * The rules every program obeys, checked against every program.
 *
 * ## Why this file rather than more per-program files
 *
 * Most of what can go wrong in a generated safety document is the same thing
 * going wrong in a different document: a British spelling in front of a Texas
 * contractor, a sentence that tells the reader what the law obliges them to
 * do, a claim that somebody has been trained. Those were caught by repeating
 * the same test in each program's own file, which worked for four programs
 * and would be absurd for sixty — and, worse, would mean a new program is
 * only as safe as whoever remembered to copy the checks into it.
 *
 * So the invariants live here and run against the registry. Adding a program
 * puts it under all of them automatically, and a program that cannot pass
 * them does not ship. What stays in a per-program file is what is genuinely
 * specific to that subject.
 *
 * ## Filling in the answers
 *
 * Every program is exercised with a complete answer set, generated by taking
 * the first option of each choice and a plausible sentence for each text
 * field. That is not a substitute for reading the prose — nothing is — but it
 * means no program can be added without at least assembling cleanly.
 */

const CONTEXT: CompanyContext = {
  companyName: "Bayou Mechanical LLC",
  trade: "Welding / fabrication",
  headcountBand: "6-10",
  operatingStates: ["TX"],
  platforms: "ISNetworld",
  hiringClients: ["Gulf Refining"],
  operations: null,
  logoUrl: null,
};

/**
 * A complete answer set, and then the same set with every boolean flipped.
 *
 * Both are needed: a conditional section only appears on one of them, and a
 * program whose optional sections were never assembled has had half its prose
 * untested.
 */
function answerSets(template: ProgramTemplate): Answers[] {
  const build = (pick: "first" | "last", booleans: "yes" | "no") => {
    let answers: Answers = {};

    // Two passes, so a question revealed by an earlier answer is also filled.
    for (let pass = 0; pass < 3; pass += 1) {
      for (const question of visibleQuestions(template, answers, CONTEXT)) {
        if (answers[question.id]) continue;

        if (question.kind === "boolean") {
          answers[question.id] = booleans;
        } else if (question.kind === "choice") {
          const options = question.options ?? [];
          const option =
            pick === "first" ? options[0] : options[options.length - 1];
          if (option) answers[question.id] = option.id;
        } else {
          answers[question.id] = "the site office and each work truck";
        }
      }

      // Drop anything a later answer made inapplicable, exactly as the real
      // action does — otherwise the validator rejects it as contradictory.
      const applicable = new Set(
        visibleQuestions(template, answers, CONTEXT).map((q) => q.id),
      );
      answers = Object.fromEntries(
        Object.entries(answers).filter(([id]) => applicable.has(id)),
      );
    }

    return answers;
  };

  return [build("first", "yes"), build("last", "no")];
}

function prose(sections: Section[]): string {
  return sections
    .flatMap((section) => [
      section.heading,
      ...section.blocks.flatMap((block) => {
        if (block.type === "paragraph") return [block.text];
        if (block.type === "bullets" || block.type === "numbered") return block.items;
        return [...block.head, ...block.rows.flat()];
      }),
    ])
    .join("\n");
}

/** Every offerable program, assembled both ways. */
function everyDocument(): { template: ProgramTemplate; sections: Section[] }[] {
  const out: { template: ProgramTemplate; sections: Section[] }[] = [];

  for (const template of offerablePrograms()) {
    for (const answers of answerSets(template)) {
      const outcome = assembleProgram({ template, answers, context: CONTEXT });

      assert.ok(
        outcome.ok,
        `${template.id} did not assemble from a complete answer set: ${JSON.stringify(
          outcome.ok ? [] : outcome.problems,
        )}`,
      );

      if (outcome.ok) out.push({ template, sections: outcome.sections });
    }
  }

  return out;
}

/* ------------------------------------------------------------------ *
 * Everything assembles
 * ------------------------------------------------------------------ */

test("every offered program assembles, with its options on and off", () => {
  const documents = everyDocument();
  assert.ok(documents.length >= offerablePrograms().length * 2);
});

test("every offered program produces a document worth sending", () => {
  for (const { template, sections } of everyDocument()) {
    assert.ok(
      sections.length >= 6,
      `${template.id} produced only ${sections.length} sections`,
    );

    const words = prose(sections).split(/\s+/).length;
    assert.ok(
      words > 500,
      `${template.id} produced ${words} words — that is a stub, not a program`,
    );
  }
});

/* ------------------------------------------------------------------ *
 * Nothing states the law
 * ------------------------------------------------------------------ */

test("no program tells the reader what the law obliges them to do", () => {
  /*
   * These documents are company policy. The company adopts them and is bound
   * by them, which is a different act from telling a contractor what a
   * regulation requires of them — and the second is the one this product must
   * never do, because it looks equally official and it is not ours to say.
   */
  for (const { template, sections } of everyDocument()) {
    const text = prose(sections);

    for (const forbidden of [
      "29 CFR",
      "1904.",
      "1910.",
      "1926.",
      "OSHA requires",
      "required by law",
      "the law requires",
      "you must",
      "legally required",
    ]) {
      assert.ok(
        !text.includes(forbidden),
        `${template.id} says "${forbidden}"`,
      );
    }
  }
});

test("sourceRef is never printed", () => {
  // Kept for our own maintenance, never rendered — it maps a section to the
  // element of a standard it exists to satisfy, which is our note and not a
  // claim about the customer.
  for (const { template, sections } of everyDocument()) {
    const text = prose(sections);
    for (const section of sections) {
      if (!section.sourceRef) continue;
      assert.ok(
        !text.includes(section.sourceRef),
        `${template.id} printed its sourceRef`,
      );
    }
  }
});

/* ------------------------------------------------------------------ *
 * Nothing claims a fact about the customer
 * ------------------------------------------------------------------ */

test("no program claims anybody has been trained or is compliant", () => {
  /*
   * The most damaging sentence available to this product. A questionnaire
   * cannot establish that a crew is competent, that a program was followed,
   * or that anybody is in compliance — those are facts about particular
   * people on particular days, and a document asserting them would be a
   * forgery the customer signed without noticing.
   */
  for (const { template, sections } of everyDocument()) {
    const text = prose(sections).toLowerCase();

    for (const claim of [
      "have been trained",
      "has been trained",
      "are fully trained",
      "in compliance with",
      "is compliant",
      "fully compliant",
      "meets all requirements",
      "satisfies the requirements",
      "have been completed",
      "certified by",
    ]) {
      assert.ok(!text.includes(claim), `${template.id} asserts "${claim}"`);
    }
  }
});

/* ------------------------------------------------------------------ *
 * It reads as American English, because the readers are American
 * ------------------------------------------------------------------ */

test("every program is written in American English", () => {
  // Caught "Recognising Good Safety Work" as a section heading, in a document
  // written for a Texas contractor.
  const british = [
    /\bprogramme\b/i,
    /\brecognis/i,
    /\bauthoris/i,
    /\borganis/i,
    /\bminimis/i,
    /\bspecialis/i,
    /\bprioritis/i,
    /\bbehaviour/i,
    /\butilis/i,
    /\bdefence\b/i,
    /\blabelled\b/i,
    /*
     * The doubled-consonant family. American English does not double the
     * final consonant before a suffix when the stress is not on that
     * syllable, which is why "cancelled" and "travelling" read as foreign to
     * the crew this document goes to.
     */
    /\bcancell/i,
    /\btravell/i,
    /\bmodell/i,
    /\bsignall/i,
    /\bfuelled\b/i,
    /\bunlabelled\b/i,
    /\bcentre\b/i,
    /\bpenalis/i,
    /\bjudgement\b/i,
    /\bfulfil\b/i,
    /\bpractise\b/i,
  ];

  for (const { template, sections } of everyDocument()) {
    const text = prose(sections);

    for (const pattern of british) {
      const found = text.match(pattern);
      assert.ok(
        !found,
        `${template.id} uses British spelling "${found?.[0]}"`,
      );
    }
  }
});

/* ------------------------------------------------------------------ *
 * Nothing leaks from how it was made
 * ------------------------------------------------------------------ */

test("no answer id or markup survives into a document", () => {
  for (const { template, sections } of everyDocument()) {
    const text = prose(sections);

    // Answer ids are internal. Seeing one means a label lookup fell through
    // and the customer is reading "safety_manager" in their own program.
    for (const question of template.questions) {
      assert.ok(
        !text.includes(question.id),
        `${template.id} printed the answer id "${question.id}"`,
      );
    }

    assert.doesNotMatch(text, /\*\*|\{\{|\$\{|<[a-z]+>/, `${template.id} leaked markup`);
    assert.doesNotMatch(text, /\bundefined\b|\bNaN\b|\[object/, `${template.id} leaked a value`);
  }
});

test("the company name reaches every program and no fixture leaks", () => {
  for (const { template, sections } of everyDocument()) {
    const text = prose(sections);

    assert.ok(
      text.includes(CONTEXT.companyName),
      `${template.id} never names the company`,
    );
    assert.ok(!text.includes("Redline"), `${template.id} leaked another fixture`);
  }
});

/* ------------------------------------------------------------------ *
 * The questionnaire stays short and answerable
 * ------------------------------------------------------------------ */

test("no questionnaire is longer than somebody will sit through", () => {
  for (const template of offerablePrograms()) {
    const shown = visibleQuestions(template, answerSets(template)[0], CONTEXT);
    assert.ok(
      shown.length <= 8,
      `${template.id} asks ${shown.length} questions`,
    );
  }
});

test("every question is answerable without knowing our vocabulary", () => {
  for (const template of PROGRAMS) {
    for (const question of template.questions) {
      assert.ok(question.prompt.trim().length > 0, `${template.id} has a blank prompt`);
      assert.ok(
        question.prompt.trim().endsWith("?"),
        `${template.id}: "${question.prompt}" is not a question`,
      );

      if (question.kind === "choice") {
        assert.ok(
          (question.options?.length ?? 0) >= 2,
          `${template.id}: "${question.id}" is a choice with fewer than two options`,
        );

        for (const option of question.options ?? []) {
          assert.ok(
            option.label.trim().length > 0,
            `${template.id}: "${question.id}" has an unlabelled option`,
          );
        }
      }
    }
  }
});

test("answer ids are recognizably internal, so a leak is detectable", () => {
  /*
   * The leak check above compares prose against every answer id. A single-word
   * id like "inspector" or "meetings" collides with ordinary English, so it
   * either false-positives on correct prose or — worse — passes only because
   * the prose happened to capitalize the word. Neither is a check.
   *
   * Requiring an underscore makes every id unmistakably ours, which is what
   * lets the leak check be strict.
   *
   * `labelling` is grandfathered. It is written into the stored answers of
   * every HazCom version already issued, and renaming it would make a revision
   * of one of those documents fail validation as a contradictory answer.
   */
  const grandfathered = new Set(["labelling"]);

  for (const template of PROGRAMS) {
    for (const question of template.questions) {
      if (grandfathered.has(question.id)) continue;

      assert.ok(
        question.id.includes("_"),
        `${template.id}: "${question.id}" reads as an ordinary word — ` +
          "give it an underscore so a leak into the prose is detectable",
      );
    }
  }
});

test("ids and titles are unique across the library", () => {
  // A duplicate id silently shadows a program; a duplicate title means a
  // customer cannot tell two documents apart in their own library.
  const ids = PROGRAMS.map((program) => program.id);
  const titles = PROGRAMS.map((program) => program.title);

  assert.equal(new Set(ids).size, ids.length, "two programs share an id");
  assert.equal(new Set(titles).size, titles.length, "two programs share a title");
});

test("every program answers to the requirement title it satisfies", () => {
  /*
   * `matchesLabel` is the join between a gap-report finding and the program
   * that answers it. A program whose matcher does not recognize its own
   * configured title is a program the product can prepare and will never
   * offer, which is invisible from the outside.
   */
  for (const template of offerablePrograms()) {
    assert.ok(
      template.matchesLabel?.(template.title) ?? false,
      `${template.id} does not match its own title "${template.title}"`,
    );
  }
});
